* Compiled Language
** Máy ảo Move (Move VM - MVM)
+ Tính năng chính:
  + Kiểu tĩnh: Move kiểm tra kiểu tại thời điểm biên dịch, giúp phát hiện lỗi sớm.
  + An toàn & Bảo mật: Nhấn mạnh quyền sở hữu tài nguyên và vay mượn, ngăn ngừa các lỗ hổng phổ biến.
  + Hiệu quả: Được tối ưu hóa cho phí gas thấp, làm cho các giao dịch rẻ hơn.
  + Đầu ra của trình biên dịch: Tạo mã bytecode chạy trên máy ảo Move.
** Solidity (Máy ảo Ethereum - EVM)
+ Tính năng chính:
  + Kiểu tĩnh & Tính năng động: Chủ yếu kiểm tra kiểu tại thời điểm biên dịch nhưng cũng hỗ trợ một số tính năng động.
  + Dựa trên hợp đồng: Được thiết kế đặc biệt để viết hợp đồng thông minh.
  + Đầu ra của trình biên dịch: Tạo mã bytecode chạy trên EVM.
** Analog đơn giản:
+ Move: Hãy nghĩ về nó như một công cụ chuyên dụng được xây dựng cho một mục đích cụ thể (bảo mật và hiệu quả), đảm bảo rằng mọi khía cạnh của thiết kế của nó đều giúp đạt được mục đích đó.
+ Solidity: Hơn như một công cụ đa năng được thiết kế cho việc sử dụng rộng rãi hơn, với các cải tiến liên tục để giải quyết bảo mật và hiệu quả.
